---

- name: journald | client | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/{{ item }}"
  with_items:
    - journal-upload.conf
  notify: 
    - restart journald
    - restart journal-upload

- name: journald | client | systemd service
  tags:
    - service
  template:
    src: "{{ item }}".j2
    dest: /etc/systemd/system/{{ item }}
  with_items: systemd-journal-upload.service
  notify: 
    - restart journal-upload

- name: journald | client | service
  tags:
    - service
  service:
    name: systemd-journal-upload
    state: started
    enabled: yes
