---

- name: journald | client | config
  tags:
    - config
  template:
    src: journal-upload.conf.j2
    dest: /etc/systemd/journal-upload.conf
  notify: 
    - restart journald
    - restart journal-upload

- name: journald | client | user
  tags:
    - user
  user:
    name: "{{ journald_user }}"
    groups: "{{ journald_user }}"
    home: /run/systemd
    system: yes
    password: "!"
    shell: /bin/false
    create_home: no

- name: journald | client | systemd service
  tags:
    - service
  template:
    src: systemd-journal-upload.service.j2
    dest: /etc/systemd/system/systemd-journal-upload.service
  notify: 
    - restart journal-upload

- name: journald | client | service
  tags:
    - service
  service:
    name: systemd-journal-upload
    state: started
    enabled: yes
