---

- name: journald | server | config
  tags:
    - config
    - systemd
  template:
    src: systemd-journal-remote.socket.j2
    dest: /etc/systemd/system/systemd-journal-remote.socket
  notify:
    - daemon-reload
    - restart journald
    - restart journal-remote

- name: journald | server | service file
  tags:
    - service
  copy:
    src: systemd-journal-remote.service
    dest: /etc/systemd/system/
  notify: 
    - daemon-reload
    - restart journal-remote

- name: journald | server | storage dir
  tags:
    - systemd
  file:
    path: /var/log/journal/remote
    state: directory
    owner: systemd-journal-remote

- name: journald | server | service
  tags:
    - service
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - systemd-journal-remote.service
    - systemd-journal-remote.socket
